ITWorld/ITWorld/Controllers/CPUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITWorld.Models;
using ITWorld.ModelView;

namespace ITWorld.Controllers
{
    public class CPUController : Controller
    {
        // GET: CPU
        Entities db = new Entities();
        public ActionResult Index()
        {
            List<Product_CPU> cpus = new List<Product_CPU>();
            cpus = db.Product_CPU.ToList();
            if (cpus.Count > 0)
            {
                int min = (int)cpus.Min(c => c.Product.Price);
                int max = (int)cpus.Max(c => c.Product.Price);
                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
            }

            return View(cpus);
        }
        [HttpPost]
        public ActionResult Index(int min, int max)
        {
            List<Product_Case> cpus = new List<Product_Case>();
            cpus = db.Product_Case.ToList();
            if (cpus.Count > 0)
            {
                min = Convert.ToInt32(Request["min"].ToString());
                max = Convert.ToInt32(Request["max"].ToString());
                int masterMin = (int)cpus.Min(c => c.Product.Price);
                int masterMax = (int)cpus.Max(c => c.Product.Price);

                ViewBag.masterMin = masterMin;
                ViewBag.masterMax = masterMax;

                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
                return View(cpus);
            }

            return View(cpus.Where(x => x.Product.Price >= min && x.Product.Price <= max).ToList());
        }


        public ActionResult ViewInfo(int? id)
        {
            return View(db.Product_CPU.Where(x => x.ID == id).FirstOrDefault());
        }
    }
}

ITWorld/ITWorld/Views/CPU/Index.cshtml
@model IEnumerable<ITWorld.Models.Product_CPU>
@{
    ViewBag.Title = "CPUs";
}

<h2>Procesoriai</h2>

<div class="container container-product">
     @using (Html.BeginForm("Index", "CPU", FormMethod.Post)) 
     { 
        if (ViewBag.Empty == null)
        {
            <div style="top :0 ; left: 0;">
                <div data-role="rangeslider">
                    <label for="price-min">Minimali kaina:</label>
                    <input type="number" name="min" value="@ViewBag.min" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                    <label for="price-max">Maksimali kaina:</label>
                    <input type="number" name="max" value="@ViewBag.max" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                </div>
                <input type="submit" value="Filtruoti" />
            </div>
        }
        else
        {
            @ViewBag.Empty
        }   
    }
    <h1 class="text-center"></h1>
    @foreach (var item in Model)
    {
        <div class="col-md-4" style="border:2px solid black">
            <div style="text-align: center; border-bottom: 2px solid maroon">
                <h3> @item.Product.Name</h3>
            </div>
            <div>
                <div class="col-md-8" style="align-content:center">
                    <img src="@Url.Content(item.Product.Image_URL)" height="200px" width="200px" />
                </div>
            </div>
            <div class="col-md-8" style="font-size: 18px; border-top: 2px solid marron; padding: 2px">
                <b>@item.Product.Price €</b>
            </div>
            <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid marron; padding: 2px">
                @Html.ActionLink("Plačiau", "ViewInfo", new { id = item.ID })
            </div>
        </div>
    }
</div>

ITWorld/ITWorld/Views/CPU/ViewInfo.cshtml
@model ITWorld.Models.Product_CPU

<h2>Procesorius</h2>

@{
    ViewBag.Title = "CPU";
}

<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            margin-top: 5rem;
            margin-bottom: 5rem;
        }

        td, th {
            border: 1px solid black;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        img {
            float: left;
            padding-right: 5px;
        }
    </style>
</head>
<body>

    <div>
        <img src="@Model.Product.Image_URL" alt="Not found" height="200px" width="200px" />
        <h2 class="text-left" style="border-bottom:none; text-align:center;">@Model.Product.Name</h2>
        <h2 class="text-left" style="border-bottom:none; text-align:center;">Kaina: @Model.Product.Price €</h2>
        <h2 class="text-left" style="border-bottom:none; text-align:center;">Kiekis sandelyje: @Model.Product.Stock</h2>

    </div>
    <div>
        <table>
            <tr>
                <td>Gamintojas</td>
                <td>@Model.Product.Manufacturer</td>
            </tr>
            <tr>
                <td>Garantija</td>
                <td>@Model.Product.Guarrantee</td>
            </tr>
            <tr>
                <td>Branduolių skaičius</td>
                <td>@Model.CoreCount</td>
            </tr>
            <tr>
                <td>L1 atmintis</td>
                <td>@Model.L1</td>
            </tr>
            @if (Model.L2 != null)
            {
                <tr>
                    <td>L2 atmintis</td>
                    <td>@Model.L2</td>
                </tr>
            }
            @if (Model.L3 != null)
            {
                <tr>
                    <td>L3 atmintis</td>
                    <td>@Model.L3</td>
                </tr>
            }
            <tr>
                <td>Tipas</td>
                <td>@Model.Generation</td>
            </tr>
            <tr>
                <td>Turbo</td>
                <td>@Model.Turbo</td>
            </tr>
            <tr>
                <td>TDP</td>
                <td>@Model.TDP</td>
            </tr>


        </table>
    </div>
    <a id="btn_add" href="@Url.Action("Add", "Shopping",new { productID = Model.Product.ID })" class="btn btn-info" style="float:right">
        <span class="glyphicon glyphicon-shopping-cart"></span> Pridėtį į krepšelį
    </a>
    <div>
        @Html.ActionLink("Grįžti atgal", "Index", new { @class = "btn btn-default" })
    </div>

</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}