ITWorld/ITWorld/Controllers/GPUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITWorld.Models;
using ITWorld.ModelView;

namespace ITWorld.Controllers
{
    public class GPUController : Controller
    {
        // GET: GPU
        Entities db = new Entities();
        public ActionResult Index()
        {
            List<Product_Graphics_Card> gpus = new List<Product_Graphics_Card>();
            gpus = db.Product_Graphics_Card.ToList();
            if (gpus.Count > 0)
            {
                int min = (int)gpus.Min(c => c.Product.Price);
                int max = (int)gpus.Max(c => c.Product.Price);
                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
            }

            return View(gpus);
        }
        [HttpPost]
        public ActionResult Index(int min, int max)
        {
            List<Product_Graphics_Card> gpus = new List<Product_Graphics_Card>();
            gpus = db.Product_Graphics_Card.ToList();
            if (gpus.Count > 0)
            {
                min = Convert.ToInt32(Request["min"].ToString());
                max = Convert.ToInt32(Request["max"].ToString());
                int masterMin = (int)gpus.Min(c => c.Product.Price);
                int masterMax = (int)gpus.Max(c => c.Product.Price);

                ViewBag.masterMin = masterMin;
                ViewBag.masterMax = masterMax;

                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
                return View(gpus);
            }

            return View(gpus.Where(x => x.Product.Price >= min && x.Product.Price <= max).ToList());
        }


        public ActionResult ViewInfo(int? id)
        {
            return View(db.Product_Graphics_Card.Where(x => x.ID == id).FirstOrDefault());
        }
    }
}

ITWorld/ITWorld/Views/GPU/Index.cshtml
@model IEnumerable<ITWorld.Models.Product_Graphics_Card>
@{
    ViewBag.Title = "GPUs";
}
<!--<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">-->
    @*<link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">*@
    <!--<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
</head>-->
<h2>Grafikos plokštės</h2>
<div class="container container-product">
    @using (Html.BeginForm("Index", "GPU", FormMethod.Post))
    {
        if (ViewBag.Empty == null)
        {
            <div style="top :0 ; left: 0;">
                <div data-role="rangeslider">
                    <label for="price-min">Minimali kaina:</label>
                    <input type="number" name="min" value="@ViewBag.min" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                    <label for="price-max">Maksimali kaina:</label>
                    <input type="number" name="max" value="@ViewBag.max" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                </div>
                <input type="submit" value="Filtruoti" />
            </div>
        }
        else
        {
            @ViewBag.Empty
        }
    }
    <h1 class="text-center"></h1>
    @foreach (var item in Model)
    {
        <div class="col-md-4" style="border:2px solid black">
            <div style="text-align: center; border-bottom: 2px solid maroon">
                <h3> @item.Product.Name</h3>
            </div>
            <div>
                <div class="col-md-8" style="align-content:center">
                    <img src="@Url.Content(item.Product.Image_URL)" height="200px" width="200px" />
                </div>
            </div>
            <div class="col-md-8" style="font-size: 18px; border-top: 2px solid marron; padding: 2px">
                <b>@item.Product.Price €</b>
            </div>
            <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid marron; padding: 2px">
                @Html.ActionLink("Plačiau", "ViewInfo", new { id = item.ID })
            </div>
        </div>
    }
</div>

ITWorld/ITWorld/Views/GPU/ViewInfo.cshtml
@model ITWorld.Models.Product_Graphics_Card

<h2>Vaizdo plokštė</h2>

@{
    ViewBag.Title = "GPU";
}

<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            margin-top: 5rem;
            margin-bottom: 5rem;
        }

        td, th {
            border: 1px solid black;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        img {
            float: left;
        }
    </style>
</head>
<body>

    <div>
        <img src="@Model.Product.Image_URL" alt="Not found" height="200px" width="200px" />
        <h2 class="text-left" style="border-bottom:none; text-align:center;">@Model.Product.Name</h2>
        <h2 class="text-left" style="border-bottom:none; text-align:center;">Kaina: @Model.Product.Price €</h2>
        <h2 class="text-left" style="border-bottom:none; text-align:center;">Kiekis sandelyje: @Model.Product.Stock</h2>

    </div>
    <div>
        <table>
            <tr>
                <td>Gamintojas</td>
                <td>@Model.Product.Manufacturer</td>
            </tr>
            <tr>
                <td>Garantija</td>
                <td>@Model.Product.Guarrantee</td>
            </tr>
            <tr>
                <td>RGB</td>
                <td>@Model.Product.Is_RGB</td>
            </tr>
            <tr>
                <td>Greitis</td>
                <td>@Model.Speed</td>
            </tr>
            <tr>
                <td>Atminties dydis</td>
                <td>@Model.Capacity</td>
            </tr>
            <tr>
                <td>BitRate</td>
                <td>@Model.BitRate</td>
            </tr>
            <tr>
                <td>PCIE prijungimai</td>
                <td>@Model.PCIE_Connection</td>
            </tr>
            <tr>
                <td>Šeima</td>
                <td>@Model.Family</td>
            </tr>
            <tr>
                <td>Išmatavimai</td>
                <td>@Model.Dimensions</td>
            </tr>
            <tr>
                <td>Tipas</td>
                <td>@Model.Type</td>
            </tr>


        </table>
        <a id="btn_add" href="@Url.Action("Add", "Shopping",new { productID = Model.Product.ID })" class="btn btn-info" style="margin-left:60px; float:right">
            <span class="glyphicon glyphicon-shopping-cart"></span> Pridėtį į krepšelį
        </a>
        <div>
            @Html.ActionLink("Grįžti atgal", "Index", new { @class = "btn btn-default" })
        </div>
    </div>

</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}