ITWorld/ITWorld/Controllers/MousepadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITWorld.Models;
using ITWorld.ModelView;

namespace ITWorld.Controllers
{
    public class MousepadController : Controller
    {
        Entities db = new Entities();
        public ActionResult Index()
        {
            List<Product_MousePad> mousepads = new List<Product_MousePad>();
            mousepads = db.Product_MousePad.ToList();
            if (mousepads.Count > 0)
            {
                int min = (int)mousepads.Min(c => c.Product.Price);
                int max = (int)mousepads.Max(c => c.Product.Price);
                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
            }

            return View(mousepads);
        }
        [HttpPost]
        public ActionResult Index(int min, int max)
        {
            List<Product_MousePad> mousepads = new List<Product_MousePad>();
            mousepads = db.Product_MousePad.ToList();
            if (mousepads.Count > 0)
            {
                min = Convert.ToInt32(Request["min"].ToString());
                max = Convert.ToInt32(Request["max"].ToString());
                int masterMin = (int)mousepads.Min(c => c.Product.Price);
                int masterMax = (int)mousepads.Max(c => c.Product.Price);

                ViewBag.masterMin = masterMin;
                ViewBag.masterMax = masterMax;

                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
                return View(mousepads);
            }

            return View(mousepads.Where(x => x.Product.Price >= min && x.Product.Price <= max).ToList());
        }


        public ActionResult ViewInfo(int? id)
        {
            return View(db.Product_MousePad.Where(x => x.ID == id).FirstOrDefault());
        }
    }
}

ITWorld/ITWorld/Views/Mousepad/Index.cshtml
@model IEnumerable<ITWorld.Models.Product_MousePad>

@{
    ViewBag.Title = "Mousepads";
}

<h2>Pelių kilimėliai</h2>

<div class="container container-product">
    @using (Html.BeginForm("Index", "Mousepad", FormMethod.Post))
    {
        if (ViewBag.Empty == null)
        {
            <div style="top :0 ; left: 0;">
                <div data-role="rangeslider">
                    <label for="price-min">Minimali kaina:</label>
                    <input type="number" name="min" value="@ViewBag.min" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                    <label for="price-max">Maksimali kaina:</label>
                    <input type="number" name="max" value="@ViewBag.max" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                </div>
                <input type="submit" value="Filtruoti" />
            </div>
        }
        else
        {
            @ViewBag.Empty
        }
    }
    <h1 class="text-center"></h1>
    @foreach (var item in Model)
    {
        <div class="col-md-4" style="border:2px solid black">
            <div style="text-align: center; border-bottom: 2px solid maroon">
                <h3> @item.Product.Name</h3>
            </div>
            <div>
                <div class="col-md-8" style="align-content:center">
                    <img src="@Url.Content(item.Product.Image_URL)" height="200px" width="200px" />
                </div>
            </div>
            <div class="col-md-8" style="font-size: 18px; border-top: 2px solid marron; padding: 2px">
                <b>@item.Product.Price €</b>
            </div>
            <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid marron; padding: 2px">
                @Html.ActionLink("Plačiau", "ViewInfo", new { id = item.ID })
            </div>
        </div>
    }
</div>

ITWorld/ITWorld/Views/Mousepad/ViewInfo.cshtml
@model ITWorld.Models.Product_MousePad

<h2>Pelės kilimėlis</h2>

@{
    ViewBag.Title = "Mousepads";
}

<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid black;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        img {
            float: left;
        }
    </style>
</head>
<body>

    <div>
        <img src="@Model.Product.Image_URL" alt="Not found" height="200px" width="200px" />
        <h2 class="text-left">@Model.Product.Name</h2>
        <a id="btn_add" href="@Url.Action("Add", "Shopping",new { productID = Model.Product.ID })" class="btn btn-info btn-lg" style="margin-left:60px; float:right">
            <span class="glyphicon glyphicon-shopping-cart"></span> Pridėtį į krepšelį
        </a>
        <h2 class="text-left">Kaina: @Model.Product.Price €</h2>
        <h2 class="text-left">Kiekis sandelyje: @Model.Product.Stock</h2>
    </div>
            <div>
                <table>
                    <tr>
                        <td>Gamintojas</td>
                        <td>@Model.Product.Manufacturer</td>
                    </tr>
                    <tr>
                        <td>Garantija</td>
                        <td>@Model.Product.Guarrantee</td>
                    </tr>
                    <tr>
                        <td>RGB</td>
                        <td>@Model.Product.Is_RGB</td>
                    </tr>
                    <tr>
                        <td>Galimybė krauti</td>
                        <td>@Model.Charge_pad</td>
                    </tr>
                    <tr>
                        <td>Dydis</td>
                        <td>@Model.Size</td>
                    </tr>
                    <tr>
                        <td>Apžvalga</td>
                        <td>@Model.Overview</td>
                    </tr>
                </table>
            </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}