ITWorld/ITWorld/Controllers/KeyboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITWorld.Models;
using ITWorld.ModelView;

namespace ITWorld.Controllers
{
    public class KeyboardController : Controller
    {
        // GET: Keyboard
        Entities db = new Entities();
        public ActionResult Index()
        {
            List<Product_Keyboard> keyboards = new List<Product_Keyboard>();
            keyboards = db.Product_Keyboard.ToList();
            if (keyboards.Count > 0)
            {
                int min = (int)keyboards.Min(c => c.Product.Price);
                int max = (int)keyboards.Max(c => c.Product.Price);
                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
            }

            return View(keyboards);
        }
        [HttpPost]
        public ActionResult Index(int min, int max)
        {
            List<Product_Keyboard> keyboards = new List<Product_Keyboard>();
            keyboards = db.Product_Keyboard.ToList();
            if (keyboards.Count > 0)
            {
                min = Convert.ToInt32(Request["min"].ToString());
                max = Convert.ToInt32(Request["max"].ToString());
                int masterMin = (int)keyboards.Min(c => c.Product.Price);
                int masterMax = (int)keyboards.Max(c => c.Product.Price);

                ViewBag.masterMin = masterMin;
                ViewBag.masterMax = masterMax;

                ViewBag.min = min;
                ViewBag.max = max;
            }
            else
            {
                ViewBag.Empty = "Tuščias sąrašas";
                return View(keyboards);
            }

            return View(keyboards.Where(x => x.Product.Price >= min && x.Product.Price <= max).ToList());
        }


        public ActionResult ViewInfo(int? id)
        {
            return View(db.Product_Keyboard.Where(x => x.ID == id).FirstOrDefault());
        }
    }
}

ITWorld/ITWorld/Views/Keyboard/Index.cshtml
@model IEnumerable<ITWorld.Models.Product_Keyboard>
@{
    ViewBag.Title = "Keyboards";
}

<h2>Klaviatūros</h2>

<div class="container container-product">
    @using (Html.BeginForm("Index", "Keyboard", FormMethod.Post))
    {
        if (ViewBag.Empty == null)
        {
            <div style="top :0 ; left: 0;">
                <div data-role="rangeslider">
                    <label for="price-min">Minimali kaina:</label>
                    <input type="number" name="min" value="@ViewBag.min" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                    <label for="price-max">Maksimali kaina:</label>
                    <input type="number" name="max" value="@ViewBag.max" min="@ViewBag.masterMin" max="@ViewBag.masterMax">
                </div>
                <input type="submit" value="Filtruoti" />
            </div>
        }
        else
        {
            @ViewBag.Empty
        }
    }
    <h1 class="text-center"></h1>
    @foreach (var item in Model)
    {
        <div class="col-md-4" style="border:2px solid black">
            <div style="text-align: center; border-bottom: 2px solid maroon">
                <h3> @item.Product.Name</h3>
            </div>
            <div>
                <div class="col-md-8" style="align-content:center">
                    <img src="@Url.Content(item.Product.Image_URL)" height="200px" width="200px" />
                </div>
            </div>
            <div class="col-md-8" style="font-size: 18px; border-top: 2px solid marron; padding: 2px">
                <b>@item.Product.Price €</b>
            </div>
            <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid marron; padding: 2px">
                @Html.ActionLink("Plačiau", "ViewInfo", new { id = item.ID })
            </div>
        </div>
    }
</div>

ITWorld/ITWorld/Views/Keyboard/ViewInfo.cshtml
@model ITWorld.Models.Product_Keyboard

<h2>Monitorius</h2>

@{
    ViewBag.Title = "Keyboard";
}

<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            margin-top: 5rem;
            margin-bottom: 5rem;
        }

        td, th {
            border: 1px solid black;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        img {
            float: left;
        }
    </style>
</head>
<body>

    <div>
        <img src="@Model.Product.Image_URL" alt="Not found" height="200px" width="200px" />
        <h2 class="text-left" style="border-bottom:none; text-align:center;">@Model.Product.Name</h2>
        <h2 class="text-left" style="border-bottom:none; text-align:center;">Kaina: @Model.Product.Price €</h2>
        <h2 class="text-left" style="border-bottom:none; text-align:center;">Kiekis sandelyje: @Model.Product.Stock</h2>
    </div>
    <div>
        <table>
            <tr>
                <td>Gamintojas</td>
                <td>@Model.Product.Manufacturer</td>
            </tr>
            <tr>
                <td>Garantija</td>
                <td>@Model.Product.Guarrantee</td>
            </tr>
            <tr>
                <td>RGB</td>
                <td>@Model.Product.Is_RGB</td>
            </tr>
            <tr>
                <td>Bekontaktės</td>
                <td>@Model.Wireless</td>
            </tr>
            <tr>
                <td>Išdėstymas</td>
                <td>@Model.Layout</td>
            </tr>
            <tr>
                <td>Dydis</td>
                <td>@Model.Size____</td>
            </tr>
            <tr>
                <td>Mygtukų tipas</td>
                <td>@Model.Switches</td>
            </tr>
            <tr>
                <td>Laido ilgis</td>
                <td>@Model.Wire_length</td>
            </tr>
            <tr>
                <td>Paspaudimo skaičius</td>
                <td>@Model.Guarantee_presses</td>
            </tr>


        </table>
        <a id="btn_add" href="@Url.Action("Add", "Shopping",new { productID = Model.Product.ID })" class="btn btn-info" style="margin-left:60px; float:right">
            <span class="glyphicon glyphicon-shopping-cart"></span> Pridėtį į krepšelį
        </a>
        <div>
            @Html.ActionLink("Grįžti atgal", "Index", new { @class = "btn btn-default" })
        </div>
    </div>

</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}